# Generated by Django 4.0.4 on 2022-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_dancer_user_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.CharField(default=1, max_length=250),
        ),
    ]
